a = int(input("Enter the First Number :" ))
b = int(input("Enter the Second Number :" ))
print("Addition: ", a + b)
print(f"Substraction:",a-b)
print(f"Multiplication: {a*b}")
print(f"Division: {a/b}")